### Numpy Array Operations

In [3]:
import numpy as np

In [19]:
#1D Array

arr = np.array([i for i in range(1, 12)])
print("Original Array = ",arr)

print(f"Slicing = {arr[2:8]}")
print(f"With Steps = {arr[1:9:2]}")
print(f"Positive Indexing = {arr[4]}")
print(f"Negative Indexing = {arr[-4]}")

#2D Array

arr_2d = np.array([[1,2,3],
                    [4,5,6]])
print(f"Original 2D Array = \n {arr_2d}")
print(f"Specific Element = {arr_2d[1,2]}")
print(f"Entire Row = {arr_2d[1]}")
print(f"Entire Column = {arr_2d[:, 2]}")


Original Array =  [ 1  2  3  4  5  6  7  8  9 10 11]
Slicing = [3 4 5 6 7 8]
With Steps = [2 4 6 8]
Positive Indexing = 5
Negative Indexing = 8
Original 2D Array = 
 [[1 2 3]
 [4 5 6]]
Specific Element = 6
Entire Row = [4 5 6]
Entire Column = [3 6]


### Sorting

In [25]:
unsorted_arr = np.array([3,2,1,1,4,5])
print(f"Sorted Array = {np.sort(unsorted_arr)}")

arr_2d_unsorted = np.array([[3,1], [8,4], [9,2]])
print(f"Sorted 2D array by Column =\n {np.sort(arr_2d_unsorted, axis=0)}") #for column sorting
print(f"Sorted 2D array by Row=\n {np.sort(arr_2d_unsorted, axis=1)}") #for row (left to right) sorting

Sorted Array = [1 1 2 3 4 5]
Sorted 2D array by Column =
 [[3 1]
 [8 2]
 [9 4]]
Sorted 2D array by Row=
 [[1 3]
 [4 8]
 [2 9]]


## Filtering

In [5]:
numbers = np.array([i for i in range(1,11)])
print("Original Array = ",numbers)
even_no = numbers % 2 == 0
print("Even number = ", numbers[even_no])

Original Array =  [ 1  2  3  4  5  6  7  8  9 10]
Even number =  [ 2  4  6  8 10]


### Filter with Mask

In [31]:
mask = numbers > 5
print(f"numbers greater than 5 = {numbers[mask]}")

numbers greater than 5 = [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [34]:
indices = [0,2,4]
print(numbers[indices])

# Where Clause in Python

where_result = np.where(numbers > 5)
print("NP where Result = ", numbers[where_result])

[1 3 5]
NP where Result =  [ 6  7  8  9 10]


In [6]:
# create a Condition Array
condition_array = np.where(numbers > 5, numbers * 2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing Data

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_array = np.concatenate((arr1,arr2))
print(combined_array)

# Add New row
orginal_Array = np.array([[1,2], [3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((orginal_Array, new_row))

print(orginal_Array)
print(with_new_row)

#Add New Column

new_col = np.array([[7], [8]])
with_new_col = np.hstack((orginal_Array, new_col))

print("With New Columns = \n", with_new_col)

#Deleting element

arr = np.array([i for i in range(11)])
print(arr)
delete = np.delete(arr,2)
print(f"Array after Deletion = {delete}")

[1 2 3 4 5 6]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With New Columns = 
 [[1 2 7]
 [3 4 8]]
[ 0  1  2  3  4  5  6  7  8  9 10]
Array after Deletion = [ 0  1  3  4  5  6  7  8  9 10]


### Array Compatibility

In [11]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8,4])
arr3 = np.array([9,8,7,6])

print(f"Compatibility Test = { np.shape(arr1) == np.shape(arr2) }")

Compatibility Test = False
