## Numpy Array and Basics

In [1]:
import numpy as np

# Arrays in Numpy

In [3]:
arr_1d = np.array([1,2,3,4,5])

print(f"This is the 1D Array = {arr_1d}")

arr_2d = np.array([[1,2,3], [4,5,6]])

print(f"2D Array = {arr_2d}")

This is the 1D Array = [1 2 3 4 5]
2D Array = [[1 2 3]
 [4 5 6]]


# List vs Numpy array

In [5]:
py_list = [1,2,3,4,5]
print(f"This is the list = {py_list * 2}")

np_array = np.array([1,2,3,4,5])
print(f"This is the Array = {np_array * 2}")


This is the list = [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
This is the Array = [ 2  4  6  8 10]


# Speed test of List and array

In [7]:
import time

start =  time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation Time", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Array Operation Time", time.time() - start)


 List Operation Time 0.14365243911743164

 Array Operation Time 0.08798861503601074


### Creating array from scratch

In [13]:
zeros = np.zeros((2,3))
print("\n ", zeros)

ones = np.ones((2,3))
print("\n ", ones)

full = np.full((2,3), 7)
print("\n ", full)

random = np.random.random((2,3))
print("\n ", random)

arange = np.arange(0, 11, 2)
print("\n ", arange)



  [[0. 0. 0.]
 [0. 0. 0.]]

  [[1. 1. 1.]
 [1. 1. 1.]]

  [[7 7 7]
 [7 7 7]]

  [[0.67931044 0.96490301 0.46207517]
 [0.78409978 0.56544616 0.02344344]]

  [ 0  2  4  6  8 10]


### Vector, Matrices and Tensor

In [16]:
vector = np.array([1,2,3,4])
print(f"\n Vector = \n {vector}")

matrix = np.array([[1,2,3],
                   [4,5,6]])

print(f"\n Matrix = \n {matrix}")

tensor = np.array([
                    [[1,2,3], [4,5,6]],
                    [[7,8,9], [2,3,4]]
                ])
print(f"\n Tensor = \n {tensor}")


 Vector = 
 [1 2 3 4]

 Matrix = 
 [[1 2 3]
 [4 5 6]]

 Tensor = 
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [2 3 4]]]


### Array  Properties

In [18]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(f"Shape = {arr.shape}")
print(f"Dimensions = {arr.ndim}")
print(f"Size = {arr.size}")
print(f"Dtype = {arr.dtype}")

Shape = (2, 3)
Dimensions = 2
Size = 6
Dtype = int64


### Array Reshaping

In [28]:
arr = np.arange(12)
print("Original Array =",arr)

reshaping = arr.reshape((3,4))
print("Reshaping Array = \n",reshaping)

flattened = reshaping.flatten() # Return Copy of Original Array
print("Flattened Array = \n",flattened)

ravelled = reshaping.ravel() # Return view instead of Copy
print("Ravelled Array =\n ",ravelled)

transverse = reshaping.T #Transverse 
print("Transverse Array = \n",transverse)

Original Array = [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaping Array = 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled Array =
  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transverse Array = 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
