In [2]:
import numpy as np
# import matplotlib.pyplot as plt

In [6]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("=== Zomato Sales Analysis ===")
print(f"\n Shape of the Data = {sales_data.shape}")
print(f"\n Sample Data of First Three Restaurant = \n {sales_data[:3]}")
print(f"\n Sample Data  = \n {sales_data[:, 1:]}")


=== Zomato Sales Analysis ===

 Shape of the Data = (5, 5)

 Sample Data of First Three Restaurant = 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 Sample Data  = 
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [15]:
#Total sales of per year

print(np.sum(sales_data, axis=0))
year_total = np.sum(sales_data[:, 1:], axis=0)
year_total_all = np.sum(year_total, axis=0)
print(year_total)
print(year_total_all)

# Minimum Sales per Restuarant
min_sales = np.min(sales_data[:, 1:], axis=1)
print(min_sales)

#maximum Sales Per Year
max_sales = np.max(sales_data[:, 1:], axis=0)
print(max_sales)

#Avg Sale Per Year[162000. 189000. 217000. 248000.]
avg_sale_per_year = np.mean(sales_data[:, 1:],axis=0)
print("Avg Sale Per Year = ",avg_sale_per_year)

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
4080000
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
Avg Sale Per Year =  [162000. 189000. 217000. 248000.]


## Cumulative Sum

In [16]:
cumsum = np.cumsum(sales_data[:, 1:], axis=0)
print(cumsum)

[[ 150000  180000  220000  250000]
 [ 270000  320000  380000  440000]
 [ 470000  550000  640000  740000]
 [ 650000  760000  880000 1010000]
 [ 810000  945000 1085000 1240000]]


## Vectors

In [20]:
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])

print(f"Sum of Vectors = {vector1 + vector2}")
print(f"Mul of Vectors = {vector1 * vector2}")
print(f"Dot Product = {np.dot(vector1, vector2)}")

#Capitalize All Array

restaurant_types = np.array(['biryani','chinese', 'pizza', 'burger', 'cafe'])

vectorized_upper = np.vectorize(str.upper)

print(f"Vectorized Upper = {vectorized_upper(restaurant_types)}")


Sum of Vectors = [ 7  9 11 13 15]
Mul of Vectors = [ 6 14 24 36 50]
Dot Product = 130
Vectorized Upper = ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']
